### ISSUE TITLE
Problem with set_language()

### ISSUE THREAD

**Issue by g3rfx** [kevinlu1248/pyate#18]
Hi,

when I try to run the following test code from `master/tests/test_algs.py`:

```
def test_lang_change():
    TermExtraction.set_language("it", "it_core_news_sm")  # italian
    for func in ALGORITHMS:
        func(CORPUS)
```

I get the following error:

```
Traceback (most recent call last):
  File "pyate_test.py", line 28, in <module>
    test_lang_change()
  File "pyate_test.py", line 23, in test_lang_change
    TermExtraction.set_language("it", "it_core_news_sm")  # italian
TypeError: set_language() takes 1 positional argument but 2 were given`
```

Thank you in advance for looking into this.

**Comment by kevinlu1248** [comment]
What Pyate version are you using? I recently gave `TermExtraction.set_language` a second positional argument of `model_name` in `pyate==0.4.1`.

**Comment by g3rfx** [comment]
I use the latest version (0.4.1) from Pypi. Looking into the source code, I think the second parameter (`model_name`) is missing in the latest version. 
In `term_extraction.py`  one reads:

```
    @staticmethod
    def set_language(language: str):
        """
        For changing the language. Currently, the DEFAULT_GENERAL_DOMAIN is still in English only.
        If you have a good dataset in another language please put it in an issue on Github.
        """
        TermExtraction.nlp = spacy.load(language)
        TermExtraction.matcher = Matcher(TermExtraction.nlp.vocab)
        TermExtraction.DEFAULT_GENERAL_DOMAIN = pd.read_csv(
            pkg_resources.resource_stream(
                __name__, f"default_general_domain.{language}.csv"
            )
        )
```

**Comment by kevinlu1248** [comment]
I updated that here https://github.com/kevinlu1248/pyate/blob/afaac0bcbd26eccd1d6f2e15e6f0dd9ed64fe920/src/pyate/term_extraction.py#L74. I believe the latest version of `pyate==0.4.1` should have two parameters as well. Could you try either building from source or reinstalling?

**Comment by g3rfx** [comment]
Building from source would solve the problem as `set_language` on GitHub indeed takes two arguments. But in the current Pypi version, the `set_language` function takes only one argument (language). I downloaded and checked it from here:
`https://pypi.org/project/pyate/#files`

**Comment by kevinlu1248** [comment]
I updated it in `pyate==0.4.2`. Hope that helps.

**Comment by g3rfx** [comment]
Thanks a lot!
