### ISSUE TITLE
UnicodeDecodeError: 'charmap' Error in pip install Windows

### ISSUE THREAD

**Issue by kr-prince** [kevinlu1248/pyate#2]
While trying to install pyate on windows using `pip install pyate` gives the below error:

```
Collecting pyate
Using cached pyate-0.3.2.tar.gz (9.2 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\anaconda3\envs\KPIAlgo\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\prince\\AppData\\Local\\Temp\\pip-install-d1tq5ym0\\pyate\\setup.py'"'"'; __file__='"'"'C:\\Users\\prince\\AppData\\Local\\Temp\\pip-install-d1tq5ym0\\pyate\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\prince\AppData\Local\Temp\pip-pip-egg-info-4plhxjxh'
         cwd: C:\Users\prince\AppData\Local\Temp\pip-install-d1tq5ym0\pyate\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\prince\AppData\Local\Temp\pip-install-d1tq5ym0\pyate\setup.py", line 4, in <module>
        long_description = f.read()
      File "D:\anaconda3\envs\KPIAlgo\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 213: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Conda Info:
```
conda version : 4.8.2
conda-build version : 3.18.11
python version : 3.7.6.final.0
platform : Win10-x64
```

However, the same installation worked fine on my Ubuntu system. 
Conda Info:
```
conda version : 4.7.10
conda-build version : 3.15.1
python version : 3.7.3.final.0
platform : linux-x64
```

**Comment by kr-prince** [comment]
I did some search related to this kind of issues and I reckon fixing the encoding in the line `long_description = f.read()` of setup.py file might be a solution, but this package does not carries that file. Looks like the setup file is created dynamically while installation, I could not get that.

**Comment by kevinlu1248** [comment]
https://github.com/kevinlu1248/pyate/commit/d83ee38ec7f4cf2baf0266865ccca52316de0aad 
Added `setup.py` sorry for the delay. I developed it on Linux but I will look into it on my Windows dual boot. @kr-prince

**Comment by kevinlu1248** [comment]
Added `encoding="utf8"` in `setup.py` seemed to have fixed it (now Pyate 0.3.4). @kr-prince

**Comment by kr-prince** [comment]
That worked well @kevinlu1248 . Thanks for the help. Please consider another suggestion. Might as well put `force=True` in line `Doc.set_extension(self.func.__name__, default=None)` of term_extraction_pipeline.py as this will prevent error in case the nlp.add_pipe gets executed twice, else we have to restart the jupyter kernel. Or you can keep it custom. 
Anyways, congrats for the awesome work you did here..!! Lets close this issue.

**Comment by kevinlu1248** [comment]
@kr-prince Added `force=True` in https://github.com/kevinlu1248/pyate/commit/17b2f6714b2e25be7d1b9cb4c314d5660e26ea20, an optional parameter `force: bool = True` to `TermExtractionPipeline.__init__` which controls whether Doc.set_extension is forced when you add it to the pipeline (as of 0.3.8).
