### ISSUE TITLE
Performance/speed issue using combo_basic

### ISSUE THREAD

**Issue by stelmath** [kevinlu1248/pyate#20]
Hello,

I am using `combo_basic` to extract the top 5 keywords from a a collection of texts, per text. My corpus is a list of strings. Each string is around 8k characters long. I have around 63k of those texts. As I am looping through that list, I am using `tqdm` for a progress bar. I notice that the processing time for each document starts to increase as time passes by. Similarly, `tqdm` shows that the iterations/second start dropping, to the point where it takes more than 1 second per document. Here is a code snippet that I am using - I have commented out the rest of the code inside the loop and only kept the `top_keywords = ...` line and the issue still persists:

```Python
# loop over the documents
for document in tqdm.tqdm(text_list):  # a list of strings
    top_keywords = combo_basic(document).sort_values(ascending=False).head(5).index.tolist()
```

Is there some sort of caching behind the scenes that makes this slow down as the documents get processed? How can I have a "clean" call of `combo_basic` every time I use it? With the current setup, it will take me 2-3 days to process the 63k documents, as it starts to really slow down after the first 2k documents or so. Thanks!

**Comment by stelmath** [comment]
@kevinlu1248 I think I found the cause of this. I will make a PR once I find some time.

**Comment by kevinlu1248** [comment]
Hi @stelmath, thanks for reporting this issue. I do not recall implementing any caching. I would ask if all the documents have 8k, or if it is varying, but it looks like you found the issue so thank you if you could make a PR and pinpoint the exact issue, which I can fix for the other algorithms as well if it is a more general problem with the implementation. Furthermore, it looks like you are currently running the algorithm one at a time, but there is a slight performance increase if you run them all at once since it will find all term candidates at once and can also use multiprocessing.

**Comment by stelmath** [comment]
Hi @kevinlu1248, thanks for the reply. 

> Furthermore, it looks like you are currently running the algorithm one at a time, but there is a slight performance increase if you run them all at once since it will find all term candidates at once and can also use multiprocessing.

Yep I see that there is a `seperate` parameter in `count_terms_from_documents()` that is `False` by default. In my case I should set this to `True` since I need keywords per single text, right? However, `separate` is not passed by `combo_basic()` down to `count_terms_from_documents()`. Anyway, I will make the PR during the weekend probably and we can discuss there. Cheers.

**Comment by kevinlu1248** [comment]
Yup that's right, I will probably document that for others wondering the same thing. Essentially, you can pass in a single string or multiple strings for the `self.corpus` when running the `count_terms_from_documents` function, where the number of times candidates appear will be counted for every string. The parameter `separate` determines if the returned value will be a list of series (1 per document) or if the counted values will be combined into a single series. This function is run behind the scenes every time `combo_basic` is called, although you can pass an already counted series into the function. I will go more into detail in the PR.

Although this may not improve the performance significantly and sacrifices a bit of precision, another performance increase is to use `basic` instead. Essentially `combo_basic` requires all the parameters of `basic` with one extra parameter. The current implementation actually takes the same amount of time as `combo_basic` and is thus suboptimal, which I am still working on.

**Comment by kevinlu1248** [comment]
Looks like PR has fixed this so I will close this issue.
