### ISSUE TITLE
Fix performance issue with multiprocessing

### ISSUE THREAD

**Issue by kevinlu1248** [kevinlu1248/pyate#24]
Addressed in https://github.com/kevinlu1248/pyate/pull/21. @stelmath, could you look into this too if you get the chance?

**Comment by stelmath** [comment]
@kevinlu1248 sure thing

**Comment by kevinlu1248** [comment]
> @kevinlu1248 sure thing

Awesome, thanks so much. I've been busy with academic commitments lately so couldn't contribute too much. Sorry about that.
