### ISSUE TITLE
FileNotFoundError lexemes.bin

### ISSUE THREAD

**Issue by nishchay47b** [kevinlu1248/pyate#27]
First in the Readme, I think the model link is not updated which is throwing 404 error, the readme link still has version 2.0.3.
I downloaded and installed with 
```bash
pip install https://github.com/kevinlu1248/pyate/releases/download/v0.4.2/en_acl_terms_sm-2.0.4.tar.gz
```
```python
nlp = spacy.load('en_acl_terms_sm')
nlp = en_acl_terms_sm.load()
```
both are throwing 
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/en_acl_terms_sm/en_acl_terms_sm-2.0.4/vocab/lexemes.bin'

**Comment by kevinlu1248** [comment]
Thanks for bringing that up. I will look into it.

**Comment by kevinlu1248** [comment]
Sorry for the delay due to academic commitments. I fixed the first issue and am currently looking into the FileNotFoundError.

**Comment by kevinlu1248** [comment]
I think I found the source of the problem: this model only works with spaCy v2.3.2 but not with spaCy v3.0. I replicated the following in a new environment:

In the command line (Ubuntu 20.04)
```bash
pip install spacy==2.3.2 https://github.com/kevinlu1248/pyate/releases/download/v0.4.2/en_acl_terms_sm-2.0.4.tar.gz
```

Then in a Python console:
```python3
import spacy
nlp = spacy.load('en_acl_terms_sm')
```

Which led to no errors. However, it looks like you had the error a while back but spaCy v3.0 only just came out (Feb 1st). Can you verify your spaCy verison?

**Comment by kevinlu1248** [comment]
I have just added spaCy V3 support in `pyate==0.5.0`.
