### ISSUE TITLE
Precision is not as good as atr4s ?

### ISSUE THREAD

**Issue by IshanUp** [kevinlu1248/pyate#28]
I ran this on the ACL rd tec 2.0 corpus and got a precision of around 50 % which is not as good as atr4s which has a 70 % precision on the same corpus. I used combo basic.

**Comment by kevinlu1248** [comment]
Thanks for sending this issue. Can you send the code you used to test this?

**Comment by IshanUp** [comment]
Actually, on further looking into this, I have realized that this is the formula that atr4s uses. It uses Average Precision and defines it like this
![image](https://user-images.githubusercontent.com/43923371/99943074-b7fbaa00-2d96-11eb-8658-716892f95acd.png)
However, the problem here is that there is that although we do get a ranking in our pyate predictions, there is no ranking in the gold data. I do not know how did they actually go about calculating average precision here. The formula uses recall at level i, however, to be able to do that we need a ranked gold label list as well (which ACL rd tec 2.0 does not provide).

**Comment by kevinlu1248** [comment]
I see. Thanks for doing the research and sharing. It looks like there is nothing for us to do regarding this issue so I will close it for now. Please let me know regarding any updates.
