### ISSUE TITLE
FileNotFoundError - default_general_domain.csv

### ISSUE THREAD

**Issue by PandaWhoCodes** [kevinlu1248/pyate#3]
I get this error after doing a pip install pyate.

`FileNotFoundError: [Errno 2] File /usr/lib/python3/dist-packages/pyate/default_general_domain.csv does not exist: '/usr/lib/python3/dist-packages/pyate/default_general_domain.csv'`

**Comment by kevinlu1248** [comment]
Can you try `ls /usr/lib/python3/dist-packages/pyate`?

**Comment by PandaWhoCodes** [comment]
`/usr/lib/python3/dist-packages/pyate` does not exist. I did it on Google Colab.
It works on my Windows PC without a hitch.

**Comment by kevinlu1248** [comment]
Thanks for your help, fixed in `pyate==0.3.9` to support all platforms.
