### ISSUE TITLE
prep != det

### ISSUE THREAD

**Issue by dblandan** [kevinlu1248/pyate#32]
I believe you will see an improvement in the patterns if you change the definition of `prep` to `{"POS": "ADP", "IS_PUNCT": False}`.

**Comment by kevinlu1248** [comment]
Thanks for pointing that out. After a bit of research I found that DET stands for determiner and ADP is adposition according to https://github.com/explosion/spaCy/blob/master/spacy/glossary.py. I will make changes accordingly.
