### ISSUE TITLE
Configuring n-grams

### ISSUE THREAD

**Issue by DrRaja** [kevinlu1248/pyate#44]
Hi, 
Can you please guide me how I can test this with different n-gram configurations? I'm using the TermExtractionPipeline with spaCy.

**Comment by kevinlu1248** [comment]
Hi there, can you elaborate a bit more on what you are trying to do? I believe you are trying to find all terms of word length n, is that correct?

**Comment by DrRaja** [comment]
Hey Kevin,
I want to experiment with different ngram configurations (bigram, trigram) to see which would produce more coherent keywords. With the default settings I think it only returns bigrams? Am I correct?

**Comment by kevinlu1248** [comment]
I see. By default (depending on the algorithm) all phrases up to length 6 are accepted. Setting the word `have_single_word` parameter would enable monograms for combo_basic, basic and cvalue and `pyate.TermExtraction.configure({"MAX_WORD_LENGTH": 7})` could set the max word length to 7, for example.

**Comment by kevinlu1248** [comment]
Does this answer your question? @DrRaja

**Comment by kevinlu1248** [comment]
No response so I'm closing.
