### ISSUE TITLE
could not read config.cfg 

### ISSUE THREAD

**Issue by micsama** [kevinlu1248/pyate#48]
need help 
error  : Could not read config.cfg from /home/dzmfg/.local/lib/python3.9/site-packages/en_core_web_sm/en_core_web_sm-2.2.5/config.cfg

**Comment by kevinlu1248** [comment]
Use spaCy v3.

**Comment by micsama** [comment]
> Use spaCy v3.
i try to install the last version of   "en_core_web_sm v3.1.0" and  everything is ok now

**Comment by micsama** [comment]
maybe the "Installation" need to  be update because i did run that and installed en_core_web_sm V2
