### ISSUE TITLE
no such file named "config.cfg" in a designated folder

### ISSUE THREAD

**Issue by alicia-lyu** [kevinlu1248/pyate#50]
<img width="784" alt="Screen Shot 2021-10-03 at 11 21 31 PM" src="https://user-images.githubusercontent.com/91839365/135761031-385decd6-1fa4-4de6-994a-14af9c058a83.png">
The code here is pasted from "Quick Start".

**Comment by micsama** [comment]
Use spaCy v3.

**Comment by alicia-lyu** [comment]
> Use spaCy v3.

Yep! I realized that just after I raised this issue. So I had it closed. Thanks anyway
