### ISSUE TITLE
The extracted terms are changed to lowercase; how to get the term frequency?

### ISSUE THREAD

**Issue by maohbao** [kevinlu1248/pyate#51]
Hi kevinlu1248,

Thanks for the project. I have two questions:

1) The extracted terms are changed to lowercase automatically, but usually we need to get the origin terms;
2) How to get the term frequency, is there a API?

Thank you!

**Comment by kevinlu1248** [comment]
I don't recall making an option to turn off lowercasing the terms automatically. To get the term frequency, either just search through the corpus once after running the respective algorithm. This could add a lot of redundant computations so if you require a performance gain one thing you could try is counting the term frequencies first using the `TermExtractor` API, then passing that into the algorithm you want to use (I would estimate this is about 30% faster). I can add more details if you would like to try the latter method.

**Comment by maohbao** [comment]
Thank you very much and I would like to see more details:)

**Comment by kevinlu1248** [comment]
Sorry for the late response. Here is an example:
```python
te = TermExtraction(CORPUS)
te.count_terms_from_documents() # this gives the pandas series for the terms to document mapping
te.cvalues() # this gives the termhood
```
