### ISSUE TITLE
PyATE 0.5.3:  general_corpus_size parameter for weirdness is ignored

### ISSUE THREAD

**Issue by bryan-johnston** [kevinlu1248/pyate#54]
In `weirdness.py` the parameter `general_corpus_size` is ignored.
This means you have to write

```
pyate.term_extraction.TermExtraction.config["DEFAULT_GENERAL_DOMAIN_SIZE"] = 5000
pyate.weirdness(text)
```

instead of just writing

`pyate.weirdness(text, general_corpus_size=5000)`

Appears to be the same issue in `term_extractor.py`.

**Comment by kevinlu1248** [comment]
Thanks for the catch.
