### ISSUE TITLE
README out of date?

### ISSUE THREAD

**Issue by christophsk** [kevinlu1248/pyate#57]
I installed spaCy 3.0.0 and per the README, ran
```
pip install pyate https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
```
Running your `combo_basic()` example resulted in an exception due to an apparent language model incompatibility. Downloading `en_core_web_sm` fixed the problem.

Maybe I missed something?

Environment: MacOs 12.2.1, Apple M1 chip, Python 3.8.11

**Comment by kevinlu1248** [comment]
Thanks for the catch and sorry for the late response. The documentation is outdated.
