### ISSUE TITLE
spaCy >= 2.3.2

### ISSUE THREAD

**Issue by g33k5z** [kevinlu1248/pyate#8]
`ERROR: pyate 0.3.9 has requirement spacy==2.2.4, but you'll have spacy 2.3.2 which is incompatible.`

Is there a pyATE release that works with newer versions of spaCy?

**Comment by kevinlu1248** [comment]
Fixed in https://github.com/kevinlu1248/pyate/commit/b885f984cafcfea5c7bba6659a783c74d82bc8f6 and `pyate==0.3.10`. The issue wasn't necessarily with the package but just `setup.py` which only allowed `spacy==2.2.4`. @g33k5z
